module.exports = {
	env: {
		BROWSER_FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
		BROWSER_FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
		BROWSER_FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
		BROWSER_FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
		BROWSER_FIREBASE_MESSAGING_SENDER_ID:
			process.env.FIREBASE_MESSAGING_SENDER_ID,
		BROWSER_FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
		BROWSER_FIREBASE_MEASUREMENT_ID:
			process.env.BROWSER_FIREBASE_MEASUREMENT_ID,
	},
	images: {
		domains: ['firebasestorage.googleapis.com'],
	},
}
