require('dotenv').config();
module.exports = {
  env: {
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
    FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
    EMAIL_JS_SERVICE: process.env.EMAIL_JS_SERVICE,
    TEMPLATE_ID: process.env.TEMPLATE_ID,
    UESR_ID: process.env.UESR_ID
  },
}
